(* A small formal test of the categorical core of Lawvere's
   "Unity and Identity of Opposites in Calculus and Physics".

   This file deliberately formalizes only the mathematical structure:
   a UI normalizes to a common retraction with two sections (a cylinder).
   It makes no claim that this structure is a complete formalization of Hegel. *)

Set Implicit Arguments.

Record Iso (A B : Type) : Type := {
  iso_forward : A -> B;
  iso_backward : B -> A;
  iso_backward_forward : forall a, iso_backward (iso_forward a) = a;
  iso_forward_backward : forall b, iso_forward (iso_backward b) = b
}.

Record Cylinder (B C : Type) : Type := {
  left_end : B -> C;
  right_end : B -> C;
  unite : C -> B;
  unite_left : forall b, unite (left_end b) = b;
  unite_right : forall b, unite (right_end b) = b
}.

(* Lawvere first defines a UI more generally: two maps into C and a third map
   out of C whose composites with the two maps are isomorphisms.  D is the
   common codomain of those two isomorphisms. *)
Record RawUI (A B C D : Type) : Type := {
  raw_left : A -> C;
  raw_right : B -> C;
  raw_unite : C -> D;
  raw_left_iso : Iso A D;
  raw_right_iso : Iso B D;
  raw_left_agrees :
    forall a, iso_forward raw_left_iso a = raw_unite (raw_left a);
  raw_right_agrees :
    forall b, iso_forward raw_right_iso b = raw_unite (raw_right b)
}.

(* Lawvere's normalization: reparametrize both ends by D.  The same uniting
   map is now literally a common retraction, so both composites are identity. *)
Definition normalize_ui {A B C D : Type} (u : RawUI A B C D) : Cylinder D C.
Proof.
  refine {| left_end := fun d => raw_left u (iso_backward (raw_left_iso u) d);
            right_end := fun d => raw_right u (iso_backward (raw_right_iso u) d);
            unite := raw_unite u |}.
  - intro d.
    rewrite <- (raw_left_agrees u (iso_backward (raw_left_iso u) d)).
    apply iso_forward_backward.
  - intro d.
    rewrite <- (raw_right_agrees u (iso_backward (raw_right_iso u) d)).
    apply iso_forward_backward.
Defined.

Section CylinderFacts.
  Context {B C : Type} (cyl : Cylinder B C).

  Definition e0 (c : C) : C := left_end cyl (unite cyl c).
  Definition e1 (c : C) : C := right_end cyl (unite cyl c).

  Theorem left_end_injective :
    forall x y, left_end cyl x = left_end cyl y -> x = y.
  Proof.
    intros x y H.
    apply (f_equal (unite cyl)) in H.
    now rewrite (unite_left cyl x), (unite_left cyl y) in H.
  Qed.

  Theorem right_end_injective :
    forall x y, right_end cyl x = right_end cyl y -> x = y.
  Proof.
    intros x y H.
    apply (f_equal (unite cyl)) in H.
    now rewrite (unite_right cyl x), (unite_right cyl y) in H.
  Qed.

  (* The two idempotents generated by the cylinder satisfy Lawvere's
     three-element-monoid equations e_i o e_j = e_i. *)
  Theorem e0_after_e0 : forall c, e0 (e0 c) = e0 c.
  Proof.
    intro c. unfold e0. now rewrite unite_left.
  Qed.

  Theorem e0_after_e1 : forall c, e0 (e1 c) = e0 c.
  Proof.
    intro c. unfold e0, e1. now rewrite unite_right.
  Qed.

  Theorem e1_after_e0 : forall c, e1 (e0 c) = e1 c.
  Proof.
    intro c. unfold e0, e1. now rewrite unite_left.
  Qed.

  Theorem e1_after_e1 : forall c, e1 (e1 c) = e1 c.
  Proof.
    intro c. unfold e1. now rewrite unite_right.
  Qed.

  (* A point lying in both ends must come from the same base point.  This is
     the elementary Set-level form of Lawvere's observation that the
     intersection is controlled by the equalizer of the two inclusions. *)
  Theorem overlap_forces_same_base :
    forall x y, left_end cyl x = right_end cyl y -> x = y.
  Proof.
    intros x y H.
    apply (f_equal (unite cyl)) in H.
    now rewrite (unite_left cyl x), (unite_right cyl y) in H.
  Qed.
End CylinderFacts.

(* The ordinary finite product cylinder: two copies of bool inside bool * bool,
   united by projection.  This is a fully enumerable instance. *)
Definition finite_product_cylinder : Cylinder bool (bool * bool).
Proof.
  refine {| left_end := fun b => (false, b);
            right_end := fun b => (true, b);
            unite := fun p => snd p |};
    intro b; reflexivity.
Defined.

Example finite_left_and_right_are_distinct :
  forall b, left_end finite_product_cylinder b <>
            right_end finite_product_cylinder b.
Proof.
  intros b H. discriminate H.
Qed.

Example finite_cylinder_monoid_test :
  forall c,
    e0 finite_product_cylinder (e1 finite_product_cylinder c) =
    e0 finite_product_cylinder c.
Proof.
  apply e0_after_e1.
Qed.
